Repository griddynamics/ui-internship-lwo2, pull requests merged in 2018-11, with the labels that each got.

#123 [A.Zhukevych]CSS_practice_task1
  css-practice/task1/css/main.css
  css-practice/task1/img/bg_hero-small.png
  css-practice/task1/img/bg_hero.png
  css-practice/task1/img/black-logo.png
  css-practice/task1/img/icon_design.svg
  css-practice/task1/img/icon_develop.svg
  css-practice/task1/img/icon_plan.svg
  css-practice/task1/img/joint.png
  css-practice/task1/img/kyiv.png
  css-practice/task1/img/label.png
  css-practice/task1/img/logo.png
  css-practice/task1/img/market.png
  css-practice/task1/img/mouse_icon.svg
  css-practice/task1/img/services_bg.png
  css-practice/task1/img/topworkz.png
  css-practice/task1/img/worktop.png
  css-practice/task1/index.html
Labels: Changes requested, Reviewed

#122 [Pavlo Turchyn] CSS-practice
  css-practice/task_1/img/about_us_border.png
  css-practice/task_1/img/design.png
  css-practice/task_1/img/development.png
  css-practice/task_1/img/header.png
  css-practice/task_1/img/joint.png
  css-practice/task_1/img/kyiv.png
  css-practice/task_1/img/lable.png
  css-practice/task_1/img/logo-bottom.png
  css-practice/task_1/img/logo.png
  css-practice/task_1/img/market.png
  css-practice/task_1/img/product.png
  css-practice/task_1/img/servises.png
  css-practice/task_1/img/sign_bottom.png
  css-practice/task_1/img/topworkz.png
  css-practice/task_1/img/worktop.png
  css-practice/task_1/index.html
  css-practice/task_1/reset.css
  css-practice/task_1/style.css
Labels: Changes requested, Reviewed

#124 [Y_Demkiv] CSS Practice Task 1
  css-practice/task 1/img/Filtro_fotografico_5_copia_2.png
  css-practice/task 1/img/facebook.png
  css-practice/task 1/img/image.png
  css-practice/task 1/img/image1.png
  css-practice/task 1/img/image2.png
  css-practice/task 1/img/image3.png
  css-practice/task 1/img/image4.png
  css-practice/task 1/img/image5.png
  css-practice/task 1/img/instagram.png
  css-practice/task 1/img/kisspng-paper-plane-airplane-computer-icons-5b0bba24de86b6.3095023015274952049115.png
  css-practice/task 1/img/send_icon.png
  css-practice/task 1/img/send_icon@3x.png
  css-practice/task 1/img/twitter.png
  css-practice/task 1/index.html
  css-practice/task 1/style.css
Labels: Changes requested, Reviewed

#125 [NATALIYA_MYKYTYUK] CSS practice task 1
  css-practice/task 1/img/design_icon.png
  css-practice/task 1/img/development_icon.png
  css-practice/task 1/img/header.png
  css-practice/task 1/img/joint.png
  css-practice/task 1/img/kyiv.png
  css-practice/task 1/img/lable.png
  css-practice/task 1/img/logo_black.png
  css-practice/task 1/img/logo_white.png
  css-practice/task 1/img/market.png
  css-practice/task 1/img/product_management_icon.png
  css-practice/task 1/img/services.png
  css-practice/task 1/img/switch_icon.png
  css-practice/task 1/img/topworkz.png
  css-practice/task 1/img/worktop.png
  css-practice/task 1/index.html
  css-practice/task 1/style.css
Labels: Changes requested, Reviewed

#130 [Eduard Hrabchak] css practice task 1
  css-practice/task1/css/adaptive.css
  css-practice/task1/css/styles.css
  css-practice/task1/img/Logo.svg
  css-practice/task1/img/USA_FLAG.jpg
  css-practice/task1/img/f-like.png
  css-practice/task1/img/f-share.png
  css-practice/task1/img/likeandsearch.png
  css-practice/task1/img/main-item.png
  css-practice/task1/img/menu.jpg
  css-practice/task1/img/pin.png
  css-practice/task1/img/sm-block.png
  css-practice/task1/img/sm-blocks.png
  css-practice/task1/img/tweet.png
  css-practice/task1/index.html
Labels: Changes requested, Reviewed

#133 [stas-molchanov] task1 initial commit
  css-practice/task1/css/style.css
  css-practice/task1/img/2-layers.png
  css-practice/task1/img/4-layers.png
  css-practice/task1/img/6-layers.png
  css-practice/task1/img/7-layers.png
  css-practice/task1/img/8-layers.png
  css-practice/task1/img/Base.png
  css-practice/task1/img/Body.png
  css-practice/task1/img/Icon.png
  css-practice/task1/img/Rectangle_1.png
  css-practice/task1/img/usa-flag.jpg
  css-practice/task1/index.html
  css-practice/task1/js/custom-select.js
  css-practice/task1/js/script.js
Labels: Ready for merge, Reviewed

#134 [stas-molchanov] CSS-practice-task_1
  css-practice/task1/css/style.css
  css-practice/task1/img/2-layers.png
  css-practice/task1/img/4-layers.png
  css-practice/task1/img/6-layers.png
  css-practice/task1/img/7-layers.png
  css-practice/task1/img/8-layers.png
  css-practice/task1/img/Base.png
  css-practice/task1/img/Body.png
  css-practice/task1/img/Icon.png
  css-practice/task1/img/Rectangle_1.png
  css-practice/task1/img/usa-flag.jpg
  css-practice/task1/index.html
  css-practice/task1/js/custom-select.js
  css-practice/task1/js/script.js
Labels: Ready for merge, Reviewed

#135 [Artur Kostiuk]css-practice-task2
  css-practice/task_2/css/main.css
  css-practice/task_2/css/main.css.map
  css-practice/task_2/img/Logo.png
  css-practice/task_2/img/Logo_big.png
  css-practice/task_2/img/Social_Media_Icons.png
  css-practice/task_2/img/avatar_2_u231.png
  css-practice/task_2/img/banner.png
  css-practice/task_2/img/cloud_load.png
  css-practice/task_2/img/cloud_upload.png
  css-practice/task_2/img/dub.png
  css-practice/task_2/img/dub_small.png
  css-practice/task_2/img/facebook_small.png
  css-practice/task_2/img/g.png
  css-practice/task_2/img/google_small.png
  css-practice/task_2/img/image.png
  css-practice/task_2/img/image_right_u255.png
  css-practice/task_2/img/img_left.png
  css-practice/task_2/img/img_right.png
  css-practice/task_2/img/inst.png
  css-practice/task_2/img/inst_small.png
  css-practice/task_2/img/keyboard.png
  css-practice/task_2/img/lightbul.png
  css-practice/task_2/img/lightning.png
  css-practice/task_2/img/main_banner.png
  css-practice/task_2/img/pint.png
  css-practice/task_2/img/pint_small.png
  css-practice/task_2/img/twitter.png
  css-practice/task_2/img/twitter_small.png
  css-practice/task_2/img/u229.png
  css-practice/task_2/img/wifi.png
  css-practice/task_2/img/wifi_small.png
  css-practice/task_2/index.html
  css-practice/task_2/index.js
  css-practice/task_2/sass/_laptopL.scss
  css-practice/task_2/sass/_mediaLaptop.scss
  css-practice/task_2/sass/_mediaTablet.scss
  css-practice/task_2/sass/_reset.scss
  css-practice/task_2/sass/_variable.scss
  css-practice/task_2/sass/main.scss
Labels: Reviewed

#143 [Eduard Hrabchak] css practise task 2
  css-practice/task2/Corporate Landing Page.psd.png
  css-practice/task2/css/media.css
  css-practice/task2/css/styles.css
  css-practice/task2/fonts/Exo-Italic.woff
  css-practice/task2/fonts/Exo-Medium.woff
  css-practice/task2/fonts/Exo-Regular.woff
  css-practice/task2/fonts/Exo-Thin.woff
  css-practice/task2/fonts/fonts.css
  css-practice/task2/img/browser-window.png
  css-practice/task2/img/features-bg.png
  css-practice/task2/img/founder-pic.png
  css-practice/task2/img/founders-bg.png
  css-practice/task2/img/header-bg.png
  css-practice/task2/img/lamp.png
  css-practice/task2/img/left-triangle.png
  css-practice/task2/img/logo.png
  css-practice/task2/img/macbook.png
  css-practice/task2/img/paper-plane.png
  css-practice/task2/img/partners.png
  css-practice/task2/img/pic-logo.png
  css-practice/task2/img/plane-logo.png
  css-practice/task2/img/play-icon.svg
  css-practice/task2/img/raw-tri.png
  css-practice/task2/img/section-7-30-days.png
  css-practice/task2/img/triangle.png
  css-practice/task2/index.html
  css-practice/task2/package-lock.json
  css-practice/task2/package.json
  css-practice/task2/scss/media.scss
  css-practice/task2/scss/styles.scss
  package-lock.json
Labels: On review

#142 [Y_Demkiv] Task 2
  css-practice/task_2/css/main.css
  css-practice/task_2/fonts/Exo-Thin.ttf
  css-practice/task_2/fonts/exo.light.otf
  css-practice/task_2/img/1.png
  css-practice/task_2/img/10.png
  css-practice/task_2/img/ARROW.png
  css-practice/task_2/img/Aenean_lacinia_bibendum_nulla_sed_consectetur._Aenean_eu_leo_qu.png
  css-practice/task_2/img/Cofee1.png
  css-practice/task_2/img/Coffee.png
  css-practice/task_2/img/Coffee_Cup.png
  css-practice/task_2/img/Earphones.png
  css-practice/task_2/img/Group_4.png
  css-practice/task_2/img/Logos.png
  css-practice/task_2/img/Pen_holder.png
  css-practice/task_2/img/Polygon_1.png
  css-practice/task_2/img/Polygon_2.png
  css-practice/task_2/img/Rectangle.png
  css-practice/task_2/img/Rectangle_21_copy.png
  css-practice/task_2/img/Rectangle_21_new.png
  css-practice/task_2/img/Shadow.png
  css-practice/task_2/img/Slice_1.png
  css-practice/task_2/img/Slice_3.png
  css-practice/task_2/img/airplane.png
  css-practice/task_2/img/bulb.png
  css-practice/task_2/img/dribbble_S.png
  css-practice/task_2/img/earphones.png
  css-practice/task_2/img/eat_logo.png
  css-practice/task_2/img/facebook_S.png
  css-practice/task_2/img/googleplus_S.png
  css-practice/task_2/img/hits_logo.png
  css-practice/task_2/img/igor_logo.png
  css-practice/task_2/img/kisspng-coffee-cup-black-coffee-cup-5aa22cf303b3e8.9451227715205777790152.png
  css-practice/task_2/img/macbook.png
  css-practice/task_2/img/partner-logo-1.png
  css-practice/task_2/img/partner-logo-4.png
  css-practice/task_2/img/partner-logo-5.png
  css-practice/task_2/img/partner-logo-7.png
  css-practice/task_2/img/partner-logo-8.png
  css-practice/task_2/img/photo-1433354359170-23a4ae7338c6.png
  css-practice/task_2/img/picture.png
  css-practice/task_2/img/rvlvr_logo.png
  css-practice/task_2/img/sienna_logo.png
  css-practice/task_2/img/twitter_S.png
  css-practice/task_2/index.html
  css-practice/task_2/sass/_media-small.scss
  css-practice/task_2/sass/_media-x-small.scss
  css-practice/task_2/sass/_media1024-1439.scss
  css-practice/task_2/sass/_media768-1023.scss
  css-practice/task_2/sass/_style.scss
  css-practice/task_2/sass/_variables.scss
  css-practice/task_2/sass/main.scss
  package-lock.json
  package.json
Labels: On review

#157 [NATALIYA_MYKYTYUK] Forms and Tabs
  css-practice/task_2/css/main.css
  css-practice/task_2/img/invalid-icon.png
  css-practice/task_2/img/valid-icon.png
  css-practice/task_2/index.html
  css-practice/task_2/sass/_style.scss
  css-practice/task_2/sass/tab-image.png
  css-practice/task_2/script.js
  package.json
Labels: Changes requested

#158 [Eduard Hrabchak] forms validation + tabs
  validation/css/main.css
  validation/css/main.css.map
  validation/img/Logo.png
  validation/img/Logo_big.png
  validation/img/Social_Media_Icons.png
  validation/img/avatar_2_u231.png
  validation/img/banner.png
  validation/img/cloud_load.png
  validation/img/cloud_upload.png
  validation/img/dub.png
  validation/img/dub_small.png
  validation/img/facebook_small.png
  validation/img/g.png
  validation/img/google_small.png
  validation/img/image.png
  validation/img/image_right_u255.png
  validation/img/img_left.png
  validation/img/img_right.png
  validation/img/inst.png
  validation/img/inst_small.png
  validation/img/keyboard.png
  validation/img/lightbul.png
  validation/img/lightning.png
  validation/img/main_banner.png
  validation/img/pint.png
  validation/img/pint_small.png
  validation/img/twitter.png
  validation/img/twitter_small.png
  validation/img/u229.png
  validation/img/wifi.png
  validation/img/wifi_small.png
  validation/index.html
  validation/index.js
  validation/sass/_laptopL.scss
  validation/sass/_mediaLaptop.scss
  validation/sass/_mediaTablet.scss
  validation/sass/_reset.scss
  validation/sass/_variable.scss
  validation/sass/main.scss
Labels: Changes requested

#159 [TARAS-YAKYMIUK]first-version-validation
  css-practice/task2-2/css/main.css
  css-practice/task2-2/css/main.css.map
  css-practice/task2-2/img/Logo.png
  css-practice/task2-2/img/Logo_big.png
  css-practice/task2-2/img/Social_Media_Icons.png
  css-practice/task2-2/img/avatar_2_u231.png
  css-practice/task2-2/img/banner.png
  css-practice/task2-2/img/cloud_load.png
  css-practice/task2-2/img/cloud_upload.png
  css-practice/task2-2/img/dub.png
  css-practice/task2-2/img/dub_small.png
  css-practice/task2-2/img/facebook_small.png
  css-practice/task2-2/img/g.png
  css-practice/task2-2/img/google_small.png
  css-practice/task2-2/img/image.png
  css-practice/task2-2/img/image_right_u255.png
  css-practice/task2-2/img/img_left.png
  css-practice/task2-2/img/img_right.png
  css-practice/task2-2/img/inst.png
  css-practice/task2-2/img/inst_small.png
  css-practice/task2-2/img/keyboard.png
  css-practice/task2-2/img/lightbul.png
  css-practice/task2-2/img/lightning.png
  css-practice/task2-2/img/main_banner.png
  css-practice/task2-2/img/pint.png
  css-practice/task2-2/img/pint_small.png
  css-practice/task2-2/img/twitter.png
  css-practice/task2-2/img/twitter_small.png
  css-practice/task2-2/img/u229.png
  css-practice/task2-2/img/wifi.png
  css-practice/task2-2/img/wifi_small.png
  css-practice/task2-2/index.html
  css-practice/task2-2/index.js
  css-practice/task2-2/sass/_laptopL.scss
  css-practice/task2-2/sass/_mediaLaptop.scss
  css-practice/task2-2/sass/_mediaTablet.scss
  css-practice/task2-2/sass/_reset.scss
  css-practice/task2-2/sass/_variable.scss
  css-practice/task2-2/sass/main.scss
Labels: Reviewed

#160 [Artur Kostiuk]Css practice task2 interactive
  css-practice/task_2/css/main.css
  css-practice/task_2/css/main.css.map
  css-practice/task_2/index.html
  css-practice/task_2/index.js
  css-practice/task_2/sass/_laptopL.scss
  css-practice/task_2/sass/_mediaLaptop.scss
  css-practice/task_2/sass/_mediaTablet.scss
Labels: Changes requested, Reviewed

#162 [Pavlo Turchyn]forms and tabs
  css-practice/task_2/css/main.css
  css-practice/task_2/index.html
  css-practice/task_2/script/script.js
  css-practice/task_2/scss/contact.scss
  css-practice/task_2/scss/features.scss
  css-practice/task_2/scss/header.scss
Labels: Changes requested, Reviewed

#164 [Nataliia Falinska] JS-task
  js-practice/css/main.css
  js-practice/css/main.css.map
  js-practice/img/Logo.png
  js-practice/img/Logo_big.png
  js-practice/img/Social_Media_Icons.png
  js-practice/img/avatar_2_u231.png
  js-practice/img/banner.png
  js-practice/img/cloud_load.png
  js-practice/img/cloud_upload.png
  js-practice/img/dub.png
  js-practice/img/dub_small.png
  js-practice/img/facebook_small.png
  js-practice/img/g.png
  js-practice/img/google_small.png
  js-practice/img/image.png
  js-practice/img/image_right_u255.png
  js-practice/img/img_left.png
  js-practice/img/img_right.png
  js-practice/img/inst.png
  js-practice/img/inst_small.png
  js-practice/img/invalid1.png
  js-practice/img/keyboard.png
  js-practice/img/lightbul.png
  js-practice/img/lightning.png
  js-practice/img/main_banner.png
  js-practice/img/pint.png
  js-practice/img/pint_small.png
  js-practice/img/twitter.png
  js-practice/img/twitter_small.png
  js-practice/img/u229.png
  js-practice/img/valid1.png
  js-practice/img/wifi.png
  js-practice/img/wifi_small.png
  js-practice/index.html
  js-practice/index.js
  js-practice/sass/_laptopL.scss
  js-practice/sass/_mediaLaptop.scss
  js-practice/sass/_mediaTablet.scss
  js-practice/sass/_reset.scss
  js-practice/sass/_variable.scss
  js-practice/sass/main.scss
  package-lock.json
  package.json
Labels: Changes requested, Reviewed

#165 [stas-molchanov]Axit tab switch and validation
  axit-interactive/css/main.css
  axit-interactive/img/avatar.png
  axit-interactive/img/avatar1.jpeg
  axit-interactive/img/avatar2.jpeg
  axit-interactive/img/avatar3.jpeg
  axit-interactive/img/bg_hero.png
  axit-interactive/img/common_icons/bulb.png
  axit-interactive/img/common_icons/download.png
  axit-interactive/img/common_icons/keyboard.png
  axit-interactive/img/common_icons/lightning.png
  axit-interactive/img/common_icons/upload.png
  axit-interactive/img/company_logo.png
  axit-interactive/img/custom_panel.png
  axit-interactive/img/icons_sprite.png
  axit-interactive/img/icons_sprite_small.png
  axit-interactive/img/image_city_1.png
  axit-interactive/img/image_city_2.png
  axit-interactive/img/skyscrapers.png
  axit-interactive/index.html
  axit-interactive/js/script.js
  axit-interactive/scss/_buttons.scss
  axit-interactive/scss/_grid-layout.scss
  axit-interactive/scss/_helper.scss
  axit-interactive/scss/_media.scss
  axit-interactive/scss/_mixins.scss
  axit-interactive/scss/_normalize.scss
  axit-interactive/scss/_s-links.scss
  axit-interactive/scss/_typography.scss
  axit-interactive/scss/_variables.scss
  axit-interactive/scss/footer/_footer.scss
  axit-interactive/scss/header/_navbar.scss
  axit-interactive/scss/main.scss
  axit-interactive/scss/sections/_about.scss
  axit-interactive/scss/sections/_contact.scss
  axit-interactive/scss/sections/_features.scss
  axit-interactive/scss/sections/_hero.scss
  axit-interactive/scss/sections/_pricing.scss
  axit-interactive/scss/sections/_reviews.scss
  axit-interactive/scss/sections/_social&custom.scss
Labels: Changes requested, Reviewed

#166 [Sophia]2nd task sass
  package.json
  template-sass/css/main.css
  template-sass/index.html
  template-sass/pics/avatar.png
  template-sass/pics/city-view-1.png
  template-sass/pics/city-view-2.png
  template-sass/pics/cloud.png
  template-sass/pics/logo-big.png
  template-sass/pics/logo-small.png
  template-sass/pics/main-background.png
  template-sass/pics/section-background.png
  template-sass/pics/skyline.png
  template-sass/script.js
  template-sass/scss/_image-sizes.scss
  template-sass/scss/_mixins.scss
  template-sass/scss/_variables.scss
  template-sass/scss/main.scss
  template-sass/scss/media/_phone.scss
  template-sass/scss/media/_tablet.scss
Labels: Reviewed

#167 [Y_Demkiv] Task 2 (forms and tabs)
  .gitignore
  css-practice/task_2_dynamic/.gitignore
  css-practice/task_2_dynamic/forms.js
  css-practice/task_2_dynamic/img/avatar.png
  css-practice/task_2_dynamic/img/banner.png
  css-practice/task_2_dynamic/img/left-image.png
  css-practice/task_2_dynamic/img/logo-big.png
  css-practice/task_2_dynamic/img/logo-small.png
  css-practice/task_2_dynamic/img/right-image.png
  css-practice/task_2_dynamic/img/small-banner.png
  css-practice/task_2_dynamic/img/tab-image.png
  css-practice/task_2_dynamic/img/tab-image2.png
  css-practice/task_2_dynamic/img/tab-image3.png
  css-practice/task_2_dynamic/index.html
  css-practice/task_2_dynamic/sass/_header.scss
  css-practice/task_2_dynamic/sass/_media.scss
  css-practice/task_2_dynamic/sass/_mixins.scss
  css-practice/task_2_dynamic/sass/_style.scss
  css-practice/task_2_dynamic/sass/_utils.scss
  css-practice/task_2_dynamic/sass/_variables.scss
  css-practice/task_2_dynamic/sass/main.scss
  css-practice/task_2_dynamic/tabs.js
  package.json
Labels: Changes requested, Reviewed

#168 [A.Zhukevych]Interactive-task1
  css-practice/task2/css/main.css
  css-practice/task2/index.html
  css-practice/task2/js/script.js
  css-practice/task2/js/validate.js
  css-practice/task2/src/pug/_includes/footer.pug
  css-practice/task2/src/pug/_includes/header.pug
  css-practice/task2/src/pug/_includes/main/about.pug
  css-practice/task2/src/pug/_includes/main/contact.pug
  css-practice/task2/src/pug/_includes/main/custom.pug
  css-practice/task2/src/pug/_includes/main/features.pug
  css-practice/task2/src/pug/_includes/main/hero.pug
  css-practice/task2/src/pug/_includes/main/pricing.pug
  css-practice/task2/src/pug/_includes/main/reviews.pug
  css-practice/task2/src/pug/_includes/main/social.pug
  css-practice/task2/src/pug/index.pug
  css-practice/task2/src/pug/script.js
  css-practice/task2/src/scss/_buttons.scss
  css-practice/task2/src/scss/_grid-layout.scss
  css-practice/task2/src/scss/_helper.scss
  css-practice/task2/src/scss/_media.scss
  css-practice/task2/src/scss/_normalize.scss
  css-practice/task2/src/scss/_s-links.scss
  css-practice/task2/src/scss/_typography.scss
  css-practice/task2/src/scss/_utility.scss
  css-practice/task2/src/scss/_variables.scss
  css-practice/task2/src/scss/footer/_footer.scss
  css-practice/task2/src/scss/header/_navbar.scss
  css-practice/task2/src/scss/main.scss
  css-practice/task2/src/scss/sections/_about.scss
  css-practice/task2/src/scss/sections/_contact.scss
  css-practice/task2/src/scss/sections/_features.scss
  css-practice/task2/src/scss/sections/_hero.scss
  css-practice/task2/src/scss/sections/_pricing.scss
  css-practice/task2/src/scss/sections/_reviews.scss
  css-practice/task2/src/scss/sections/_social&custom.scss
  css-practice/task3/src/scss/abstract/_variables.scss
  css-practice/task3/src/scss/base/_quote-slide.scss
  css-practice/task3/src/scss/base/_typography.scss
  css-practice/task3/src/scss/sections/_blog.scss
  css-practice/task3/src/scss/sections/_footer.scss
  package.json
Labels: Changes requested, Reviewed
