Repository griddynamics/ui-internship-lwo2, pull requests merged in 2018-10, with the labels that each got.

#7 [STAS-MOLCHANOV]Tasks 1 10
  .editorconfig
  .eslintrc.json
  README.md
  package.json
  tasks/10_remove-whitespaces/remove-whitespaces.js
  tasks/10_remove-whitespaces/remove-whitespaces.spec.js
  tasks/1_golf-score/golf-score.js
  tasks/1_golf-score/golf-score.spec.js
  tasks/2_convert-to-f/convert-to-f.js
  tasks/2_convert-to-f/convert-to-f.spec.js
  tasks/3_is-boolean/is-boolean.js
  tasks/3_is-boolean/is-boolean.spec.js
  tasks/4_stand-in-line/stand-in-line.js
  tasks/4_stand-in-line/stand-in-line.spec.js
  tasks/5_profile-lookup/profile-lookup.js
  tasks/5_profile-lookup/profile-lookup.spec.js
  tasks/6_reverse-string/reverse-string.js
  tasks/6_reverse-string/reverse-string.spec.js
  tasks/7_random-fraction/random-fraction.js
  tasks/7_random-fraction/random-fraction.spec.js
  tasks/8_factorize-number/factorize-number.js
  tasks/8_factorize-number/factorize-number.spec.js
  tasks/9_find-numbers/find-numbers.js
  tasks/9_find-numbers/find-numbers.spec.js
Labels: Reviewed

#4 First 10 tasks
  package-lock.json
  tasks/10_remove-whitespaces/remove-whitespaces.js
  tasks/10_remove-whitespaces/remove-whitespaces.spec.js
  tasks/11_find-longest-word/find-longest-word.js
  tasks/11_find-longest-word/find-longest-word.spec.js
  tasks/1_golf-score/golf-score.js
  tasks/1_golf-score/golf-score.spec.js
  tasks/2_convert-to-f/convert-to-f.js
  tasks/2_convert-to-f/convert-to-f.spec.js
  tasks/3_is-boolean/is-boolean.js
  tasks/3_is-boolean/is-boolean.spec.js
  tasks/4_stand-in-line/stand-in-line.js
  tasks/4_stand-in-line/stand-in-line.spec.js
  tasks/6_reverse-string/reverse-string.js
  tasks/6_reverse-string/reverse-string.spec.js
  tasks/7_random-fraction/random-fraction.js
  tasks/7_random-fraction/random-fraction.spec.js
  tasks/8_factorize-number/factorize-number.js
  tasks/8_factorize-number/factorize-number.spec.js
  tasks/9_find-numbers/find-numbers.js
  tasks/9_find-numbers/find-numbers.spec.js
Labels: Needs review, Ready for merge, Reviewed

#8 Tasks 1 10
  .editorconfig
  .eslintrc.json
  README.md
  package-lock.json
  package.json
  tasks/10_remove-whitespaces/remove-whitespaces.js
  tasks/10_remove-whitespaces/remove-whitespaces.spec.js
  tasks/1_golf-score/golf-score.js
  tasks/1_golf-score/golf-score.spec.js
  tasks/2_convert-to-f/convert-to-f.js
  tasks/2_convert-to-f/convert-to-f.spec.js
  tasks/3_is-boolean/is-boolean.js
  tasks/3_is-boolean/is-boolean.spec.js
  tasks/4_stand-in-line/stand-in-line.js
  tasks/4_stand-in-line/stand-in-line.spec.js
  tasks/5_profile-lookup/profile-lookup.js
  tasks/5_profile-lookup/profile-lookup.spec.js
  tasks/6_reverse-string/reverse-string.js
  tasks/6_reverse-string/reverse-string.spec.js
  tasks/7_random-fraction/random-fraction.js
  tasks/7_random-fraction/random-fraction.spec.js
  tasks/8_factorize-number/factorize-number.js
  tasks/8_factorize-number/factorize-number.spec.js
  tasks/9_find-numbers/find-numbers.js
  tasks/9_find-numbers/find-numbers.spec.js
Labels: Ready for merge

#15 Tasks 1 10
  tasks/10_remove-whitespaces/remove-whitespaces.js
  tasks/10_remove-whitespaces/remove-whitespaces.spec.js
  tasks/1_golf-score/golf-score.js
  tasks/1_golf-score/golf-score.spec.js
  tasks/2_convert-to-f/convert-to-f.js
  tasks/2_convert-to-f/convert-to-f.spec.js
  tasks/3_is-boolean/is-boolean.js
  tasks/3_is-boolean/is-boolean.spec.js
  tasks/4_stand-in-line/stand-in-line.js
  tasks/4_stand-in-line/stand-in-line.spec.js
  tasks/5_profile-lookup/profile-lookup.js
  tasks/5_profile-lookup/profile-lookup.spec.js
  tasks/6_reverse-string/reverse-string.js
  tasks/6_reverse-string/reverse-string.spec.js
  tasks/7_random-fraction/random-fraction.js
  tasks/7_random-fraction/random-fraction.spec.js
  tasks/8_factorize-number/factorize-number.js
  tasks/8_factorize-number/factorize-number.spec.js
  tasks/9_find-numbers/find-numbers.js
  tasks/9_find-numbers/find-numbers.spec.js
Labels: Changes requested

#9 first 10 task
  package-lock.json
  tasks/10_remove-whitespaces/remove-whitespaces.js
  tasks/10_remove-whitespaces/remove-whitespaces.spec.js
  tasks/1_golf-score/golf-score.spec.js
  tasks/1_golf-score/golf_score.js
  tasks/2_convert-to-f/convert-to-f.spec.js
  tasks/2_convert-to-f/convert.js
  tasks/3_is-boolean/is-boolean.js
  tasks/3_is-boolean/is-boolean.spec.js
  tasks/4_stand-in-line/stand-in-line.js
  tasks/4_stand-in-line/stand-in-line.spec.js
  tasks/5_profile-lookup/profile-lookup.js
  tasks/5_profile-lookup/profile-lookup.spec.js
  tasks/6_reverse-string/reverse-string.js
  tasks/6_reverse-string/reverse-string.spec.js
  tasks/7_random-fraction/random-fraction.js
  tasks/7_random-fraction/random-fraction.spec.js
  tasks/8_factorize-number/factorize-number.js
  tasks/8_factorize-number/factorize-number.spec.js
  tasks/9_find-numbers/find-numbers.js
  tasks/9_find-numbers/find-numbers.spec.js
  tasks/_sample/_sample.js
  tasks/_sample/_sample.spec.js
Labels: Ready for merge, Reviewed

#10 tasks 11-20
  tasks/11_find-longest-word/find-longest-word.js
  tasks/11_find-longest-word/find-longest-word.spec.js
  tasks/12_title-case/title-case.js
  tasks/12_title-case/title-case.spec.js
  tasks/13_largest-of-four/largest-of-four.js
  tasks/13_largest-of-four/largest-of-four.spec.js
  tasks/14_clone-arr/clone-arr.js
  tasks/14_clone-arr/clone-arr.spec.js
  tasks/15_confirm-ending/confirm-ending.js
  tasks/15_confirm-ending/confirm-ending.spec.js
  tasks/16_repeat-string/repeat-string.js
  tasks/16_repeat-string/repeat-string.spec.js
  tasks/17_truncate-string/truncate-string.js
  tasks/17_truncate-string/truncate-string.spec.js
  tasks/18_humanize-format/humanize-format.js
  tasks/18_humanize-format/humanize-format.spec.js
  tasks/19_array-chunks/array-chunks.js
  tasks/19_array-chunks/array-chunks.spec.js
  tasks/20_truncate-array/truncate-array.js
  tasks/20_truncate-array/truncate-array.spec.js
Labels: Ready for merge, Reviewed

#12 Tasks12 22
  .editorconfig
  .eslintrc.json
  README.md
  tasks/10_remove-whitespaces/remove-whitespaces.js
  tasks/10_remove-whitespaces/remove-whitespaces.spec.js
  tasks/11_find-longest-word/find-longest-word.js
  tasks/11_find-longest-word/find-longest-word.spec.js
  tasks/12_title-case/title-case.js
  tasks/12_title-case/title-case.spec.js
  tasks/13_largest-of-four/largest-of-four.js
  tasks/13_largest-of-four/largest-of-four.spec.js
  tasks/14_clone-arr/clone-arr.js
  tasks/14_clone-arr/clone-arr.spec.js
  tasks/15_confirm-ending/confirm-ending.js
  tasks/15_confirm-ending/confirm-ending.spec.js
  tasks/16_repeat-string/repeat-string.js
  tasks/16_repeat-string/repeat-string.spec.js
  tasks/17_truncate-string/truncate-string.js
  tasks/17_truncate-string/truncate-string.spec.js
  tasks/18_humanize-format/humanize-format.js
  tasks/18_humanize-format/humanize-format.spec.js
  tasks/19_array-chunks/array-chunks.js
  tasks/19_array-chunks/array-chunks.spec.js
  tasks/1_golf-score/golf-score.js
  tasks/1_golf-score/golf-score.spec.js
  tasks/20_truncate-array/truncate-array.js
  tasks/20_truncate-array/truncate-array.spec.js
  tasks/22_remove-falsy-values/remove-falsy-values.js
  tasks/22_remove-falsy-values/remove-falsy-values.spec.js
  tasks/2_convert-to-f/convert-to-f.js
  tasks/2_convert-to-f/convert-to-f.spec.js
  tasks/3_is-boolean/is-boolean.js
  tasks/3_is-boolean/is-boolean.spec.js
  tasks/4_stand-in-line/stand-in-line.js
  tasks/4_stand-in-line/stand-in-line.spec.js
  tasks/5_profile-lookup/lookupProfile.js
  tasks/6_reverse-string/reverse-string.js
  tasks/6_reverse-string/reverse-string.spec.js
  tasks/7_random-fraction/random-fraction.js
  tasks/7_random-fraction/random-fraction.spec.js
  tasks/8_factorize-number/factorize-number.js
  tasks/8_factorize-number/factorize-number.spec.js
  tasks/9_find-numbers/find-numbers.js
  tasks/9_find-numbers/find-numbers.spec.js
Labels: Ready for merge, Reviewed

#28 [Y_Demkiv] Tasks_11_20
  .editorconfig
  .eslintrc.json
  README.md
  tasks/11_find-longest-word/find-longest-word.js
  tasks/11_find-longest-word/find-longest-word.spec.js
  tasks/12_title-case/title-case.js
  tasks/12_title-case/title-case.spec.js
  tasks/13_largest-of-four/largest-of-four.js
  tasks/13_largest-of-four/largest-of-four.spec.js
  tasks/14_clone-arr/clone-arr.js
  tasks/14_clone-arr/clone-arr.spec.js
  tasks/15_confirm-ending/confirm-ending.js
  tasks/15_confirm-ending/confirm-ending.spec.js
  tasks/16_repeat-string/repeat-string.js
  tasks/16_repeat-string/repeat-string.spec.js
  tasks/17_truncate-string/truncate-string.js
  tasks/17_truncate-string/truncate-string.spec.js
  tasks/18_humanize-format/humanize-format.js
  tasks/18_humanize-format/humanize-format.spec.js
  tasks/19_array-chunks/array-chunks.js
  tasks/19_array-chunks/array-chunks.spec.js
  tasks/20_truncate-array/truncate-array.js
  tasks/20_truncate-array/truncate-array.spec.js
Labels: Reviewed

#5 [NATALIYA_MYKYTYUK] First 10 tasks
  package-lock.json
  tasks/10_remove-whitespaces/remove-whitespaces.js
  tasks/10_remove-whitespaces/remove-whitespaces.spec.js
  tasks/1_golf-score/golf-score.js
  tasks/1_golf-score/golf-score.spec.js
  tasks/2_convert-to-f/convert-to-f.js
  tasks/2_convert-to-f/convert-to-f.spec.js
  tasks/3_is-boolean/is-boolean.js
  tasks/3_is-boolean/is-boolean.spec.js
  tasks/4_stand-in-line/stand-in-line.js
  tasks/4_stand-in-line/stand-in-line.spec.js
  tasks/5_profile-lookup/profile-lookup.js
  tasks/5_profile-lookup/profile-lookup.spec.js
  tasks/6_reverse-string/reverse-string.js
  tasks/6_reverse-string/reverse-string.spec.js
  tasks/7_random-fraction/random-fraction.js
  tasks/7_random-fraction/random-fraction.spec.js
  tasks/8_factorize-number/factorize-number.js
  tasks/8_factorize-number/factorize-number.spec.js
  tasks/9_find-numbers/find-numbers.js
  tasks/9_find-numbers/find-numbers.spec.js
  tasks/_sample/_sample.spec.js
Labels: Changes requested

#17 [NATALIYA_MYKYTYUK] Tasks 11-20
  .editorconfig
  .eslintrc.json
  README.md
  package-lock.json
  tasks/11_find-longest-word/find-longest-word.js
  tasks/11_find-longest-word/find-longest-word.spec.js
  tasks/12_title-case/title-case.js
  tasks/12_title-case/title-case.spec.js
  tasks/13_largest-of-four/largest-of-four.js
  tasks/13_largest-of-four/largest-of-four.spec.js
  tasks/14_clone-arr/clone-arr.js
  tasks/14_clone-arr/clone-arr.spec.js
  tasks/15_confirm-ending/confirm-ending.js
  tasks/15_confirm-ending/confirm-ending.spec.js
  tasks/16_repeat-string/repeat-string.js
  tasks/16_repeat-string/repeat-string.spec.js
  tasks/17_truncate-string/truncate-string.js
  tasks/17_truncate-string/truncate-string.spec.js
  tasks/18_humanize-format/humanize-format.js
  tasks/18_humanize-format/humanize-format.spec.js
  tasks/19_array-chunks/array-chunks.js
  tasks/19_array-chunks/array-chunks.spec.js
  tasks/20_truncate-array/truncate-array.js
  tasks/20_truncate-array/truncate-array.spec.js
Labels: Ready for merge, Reviewed

#20 [pavlo_turchyn]Task 11 20
  tasks/11_find-longest-word/find-longest-word.js
  tasks/11_find-longest-word/find-longest-word.spec.js
  tasks/12_title-case/title-case.js
  tasks/12_title-case/title-case.spec.js
  tasks/13_largest-of-four/largest-of-four.js
  tasks/13_largest-of-four/largest-of-four.spec.js
  tasks/14_clone-arr/clone-arr.js
  tasks/14_clone-arr/clone-arr.spec.js
  tasks/15_confirm-ending/confirm-ending.js
  tasks/15_confirm-ending/confirm-ending.spec.js
  tasks/16_repeat-string/repeat-string.js
  tasks/16_repeat-string/repeat-string.spec.js
  tasks/17_truncate-string/truncate-string.js
  tasks/17_truncate-string/truncate-string.spec.js
  tasks/18_humanize-format/README.md
  tasks/18_humanize-format/humanize-format.js
  tasks/18_humanize-format/humanize-format.spec.js
  tasks/19_array-chunks/README.md
  tasks/19_array-chunks/array-chunks.js
  tasks/19_array-chunks/array-chunks.spec.js
  tasks/20_truncate-array/README.md
  tasks/20_truncate-array/truncate-array.js
  tasks/20_truncate-array/truncate-array.spec.js
  tasks/21_check-letters/check-letters.spec.js
  tasks/5_profile-lookup/profile-lookup.js
  tasks/8_factorize-number/factorize-number.js
  tasks/9_find-numbers/find-numbers.js
  tasks/_sample/_sample.js
Labels: Ready for merge, Reviewed

#22 [Nataliia Falinska] Tasks 11_20
  tasks/11_find-longest-word/find-longest-word.js
  tasks/11_find-longest-word/find-longest-word.spec.js
  tasks/12_title-case/title-case.js
  tasks/12_title-case/title-case.spec.js
  tasks/13_largest-of-four/largest-of-four.js
  tasks/13_largest-of-four/largest-of-four.spec.js
  tasks/14_clone-arr/clone-arr.js
  tasks/14_clone-arr/clone-arr.spec.js
  tasks/15_confirm-ending/confirm-ending.js
  tasks/15_confirm-ending/confirm-ending.spec.js
  tasks/16_repeat-string/repeat-string.js
  tasks/16_repeat-string/repeat-string.spec.js
  tasks/17_truncate-string/truncate-string.js
  tasks/17_truncate-string/truncate-string.spec.js
  tasks/18_humanize-format/humanize-format.js
  tasks/18_humanize-format/humanize-format.spec.js
  tasks/19_array-chunks/array-chunks.js
  tasks/19_array-chunks/array-chunks.spec.js
  tasks/20_truncate-array/truncate-array.js
  tasks/20_truncate-array/truncate-array.spec.js
  tasks/22_remove-falsy-values/remove-falsy-values.spec.js
Labels: Ready for merge, Reviewed

#24 [ANDRIY_ZHUKEVYCH] Fixed tasks 11-20
  tasks/11_find-longest-word/find-longest-word.js
  tasks/12_title-case/title-case.js
  tasks/13_largest-of-four/largest-of-four.js
  tasks/15_confirm-ending/confirm-ending.js
  tasks/18_humanize-format/humanize-format.js
Labels: Ready for merge, Reviewed

#16 [Sophia]Tasks 11 to 20
  .editorconfig
  .eslintrc.json
  README.md
  tasks/11_find-longest-word/find-longest-word.js
  tasks/11_find-longest-word/find-longest-word.spec.js
  tasks/12_title-case/title-case.js
  tasks/12_title-case/title-case.spec.js
  tasks/13_largest-of-four/largest-of-four.js
  tasks/13_largest-of-four/largest-of-four.spec.js
  tasks/14_clone-arr/clone-arr.js
  tasks/14_clone-arr/clone-arr.spec.js
  tasks/15_confirm-ending/confirm-ending.js
  tasks/15_confirm-ending/confirm-ending.spec.js
  tasks/16_repeat-string/repeat-string.js
  tasks/16_repeat-string/repeat-string.spec.js
  tasks/17_truncate-string/truncate-string.js
  tasks/17_truncate-string/truncate-string.spec.js
  tasks/18_humanize-format/humanize-format.js
  tasks/18_humanize-format/humanize-format.spec.js
  tasks/19_array-chunks/array-chunks.js
  tasks/19_array-chunks/array-chunks.spec.js
  tasks/20_truncate-array/truncate-array.js
  tasks/20_truncate-array/truncate-array.spec.js
Labels: Changes requested, Reviewed

#25 [ANDRIY_ZHUKEVYCH]Tasks 21-30
  tasks/21_check-letters/check-letters.js
  tasks/21_check-letters/check-letters.spec.js
  tasks/22_remove-falsy-values/remove-falsy-values.js
  tasks/22_remove-falsy-values/remove-falsy-values.spec.js
  tasks/23_seek-destroy/seek-destroy.js
  tasks/23_seek-destroy/seek-destroy.spec.js
  tasks/24_index-to-insert/index-to-insert.js
  tasks/24_index-to-insert/index-to-insert.spec.js
  tasks/25_rot13-encoder/rot13-encoder.js
  tasks/25_rot13-encoder/rot13-encoder.spec.js
  tasks/26_average-mark/average-mark.js
  tasks/26_average-mark/average-mark.spec.js
  tasks/27_basic-subclasses/basic-subclasses.js
  tasks/27_basic-subclasses/basic-subclasses.spec.js
  tasks/28_vowel-count/vowel-count.js
  tasks/28_vowel-count/vowel-count.spec.js
  tasks/29_remove-duplicates/remove-duplicates.js
  tasks/29_remove-duplicates/remove-duplicates.spec.js
  tasks/30_people-in-bus/people-in-bus.js
  tasks/30_people-in-bus/people-in-bus.spec.js
Labels: Ready for merge, Reviewed

#26 [Eduard Hrabchak] tasks 21-30 (without 22)
  tasks/21_check-letters/check-letters.js
  tasks/21_check-letters/check-letters.spec.js
  tasks/23_seek-destroy/seek-destroy.js
  tasks/23_seek-destroy/seek-destroy.spec.js
  tasks/24_index-to-insert/index-to-insert.js
  tasks/24_index-to-insert/index-to-insert.spec.js
  tasks/25_rot13-encoder/rot13-encoder.js
  tasks/25_rot13-encoder/rot13-encoder.spec.js
  tasks/26_average-mark/average-mark.js
  tasks/26_average-mark/average-mark.spec.js
  tasks/27_basic-subclasses/basic-subclasses.js
  tasks/27_basic-subclasses/basic-subclasses.spec.js
  tasks/28_vowel-count/vowel-count.js
  tasks/28_vowel-count/vowel-count.spec.js
  tasks/29_remove-duplicates/remove-duplicates.js
  tasks/29_remove-duplicates/remove-duplicates.spec.js
  tasks/30_people-in-bus/people-in-bus.js
  tasks/30_people-in-bus/people-in-bus.spec.js
Labels: Changes requested, Reviewed

#30 [Y_Demkiv]Tasks_21_30
  tasks/21_check-letters/check-letters.js
  tasks/21_check-letters/check-letters.spec.js
  tasks/22_remove-falsy-values/remove-falsy-values.js
  tasks/22_remove-falsy-values/remove-falsy-values.spec.js
  tasks/23_seek-destroy/seek-destroy.js
  tasks/23_seek-destroy/seek-destroy.spec.js
  tasks/24_index-to-insert/index-to-insert.js
  tasks/24_index-to-insert/index-to-insert.spec.js
  tasks/25_rot13-encoder/rot13-encoder.js
  tasks/25_rot13-encoder/rot13-encoder.spec.js
  tasks/26_average-mark/average-mark.js
  tasks/26_average-mark/average-mark.spec.js
  tasks/27_basic-subclasses/basic-subclasses.js
  tasks/27_basic-subclasses/basic-subclasses.spec.js
  tasks/28_vowel-count/vowel-count.js
  tasks/28_vowel-count/vowel-count.spec.js
  tasks/29_remove-duplicates/remove-duplicates.js
  tasks/29_remove-duplicates/remove-duplicates.spec.js
  tasks/30_people-in-bus/people-in-bus.js
  tasks/30_people-in-bus/people-in-bus.spec.js
Labels: Needs review

#37 [STAS-MOLCHANOV] tasks 21-30
  tasks/21_check-letters/check-letters.js
  tasks/21_check-letters/check-letters.spec.js
  tasks/22_remove-falsy-values/remove-falsy-values.js
  tasks/22_remove-falsy-values/remove-falsy-values.spec.js
  tasks/23_seek-destroy/seek-destroy.js
  tasks/23_seek-destroy/seek-destroy.spec.js
  tasks/24_index-to-insert/index-to-insert.js
  tasks/24_index-to-insert/index-to-insert.spec.js
  tasks/25_rot13-encoder/rot13-encoder.js
  tasks/25_rot13-encoder/rot13-encoder.spec.js
  tasks/26_average-mark/average-mark.js
  tasks/26_average-mark/average-mark.spec.js
  tasks/27_basic-subclasses/basic-subclasses.js
  tasks/27_basic-subclasses/basic-subclasses.spec.js
  tasks/28_vowel-count/vowel-count.js
  tasks/28_vowel-count/vowel-count.spec.js
  tasks/29_remove-duplicates/remove-duplicates.js
  tasks/29_remove-duplicates/remove-duplicates.spec.js
  tasks/30_people-in-bus/people-in-bus.js
  tasks/30_people-in-bus/people-in-bus.spec.js
Labels: Needs review, Ready for merge, Reviewed

#47 [Y_Demkiv] Tasks 31-40 without 37
  tasks/31_reverse-string-in-range/reverse-string-in-range.js
  tasks/31_reverse-string-in-range/reverse-string-in-range.spec.js
  tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.js
  tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.spec.js
  tasks/33_array-plus-array/array-plus-array.js
  tasks/33_array-plus-array/array-plus-array.spec.js
  tasks/34_max-triplet-sum/max-triplet-sum.js
  tasks/34_max-triplet-sum/max-triplet-sum.spec.js
  tasks/35_array-leaders/array-leaders.js
  tasks/35_array-leaders/array-leaders.spec.js
  tasks/36_row-weight/row-weight.js
  tasks/36_row-weight/row-weight.spec.js
  tasks/38_max-product/max-product.js
  tasks/38_max-product/max-product.spec.js
  tasks/39_unique-in-order/unique-in-order.js
  tasks/39_unique-in-order/unique-in-order.spec.js
  tasks/40_find-friend/find-friend.js
  tasks/40_find-friend/find-friend.spec.js
Labels: Ready for merge, Reviewed

#33 [ANDRIY_ZHUKEVYCH] Tasks 31-40
  tasks/31_reverse-string-in-range/reverse-string-in-range.js
  tasks/31_reverse-string-in-range/reverse-string-in-range.spec.js
  tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.js
  tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.spec.js
  tasks/33_array-plus-array/array-plus-array.js
  tasks/33_array-plus-array/array-plus-array.spec.js
  tasks/34_max-triplet-sum/max-triplet-sum.js
  tasks/34_max-triplet-sum/max-triplet-sum.spec.js
  tasks/35_array-leaders/array-leaders.js
  tasks/35_array-leaders/array-leaders.spec.js
  tasks/36_row-weight/row-weight.js
  tasks/36_row-weight/row-weight.spec.js
  tasks/37_min-number-to-prime/min-number-to-prime.js
  tasks/37_min-number-to-prime/min-number-to-prime.spec.js
  tasks/38_max-product/max-product.js
  tasks/38_max-product/max-product.spec.js
  tasks/39_unique-in-order/unique-in-order.js
  tasks/39_unique-in-order/unique-in-order.spec.js
  tasks/40_find-friend/find-friend.js
  tasks/40_find-friend/find-friend.spec.js
Labels: Changes requested, Reviewed

#40 [Eduard Hrabchak] tasks 31-40
  tasks/31_reverse-string-in-range/reverse-string-in-range.js
  tasks/31_reverse-string-in-range/reverse-string-in-range.spec.js
  tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.js
  tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.spec.js
  tasks/33_array-plus-array/array-plus-array.js
  tasks/33_array-plus-array/array-plus-array.spec.js
  tasks/34_max-triplet-sum/max-triplet-sum.js
  tasks/34_max-triplet-sum/max-triplet-sum.spec.js
  tasks/35_array-leaders/array-leaders.js
  tasks/35_array-leaders/array-leaders.spec.js
  tasks/36_row-weight/row-weight.js
  tasks/36_row-weight/row-weight.spec.js
  tasks/37_min-number-to-prime/min-number-to-prime.js
  tasks/37_min-number-to-prime/min-number-to-prime.spec.js
  tasks/38_max-product/max-product.js
  tasks/38_max-product/max-product.spec.js
  tasks/39_unique-in-order/unique-in-order.js
  tasks/39_unique-in-order/unique-in-order.spec.js
  tasks/40_find-friend/find-friend.js
  tasks/40_find-friend/find-friend.spec.js
Labels: Ready for merge, Reviewed

#42 [Sophia]Tasks 51 to 60
  tasks/51_abbreviated-name/abbreviated-name.js
  tasks/51_abbreviated-name/abbreviated-name.spec.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.spec.js
  tasks/53_diff-array/diff-array.js
  tasks/53_diff-array/diff-array.spec.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.spec.js
  tasks/55_find-object-analogy/find-object-analogy.js
  tasks/55_find-object-analogy/find-object-analogy.spec.js
  tasks/56_search-and-replace/search-and-replace.js
  tasks/56_search-and-replace/search-and-replace.spec.js
  tasks/57_pig-latin/pig-latin.js
  tasks/57_pig-latin/pig-latin.spec.js
  tasks/58_missed-letters/missed-letters.js
  tasks/58_missed-letters/missed-letters.spec.js
  tasks/59_sorted-sequence/sorted-sequence.js
  tasks/59_sorted-sequence/sorted-sequence.spec.js
  tasks/60_convert-html-entities/convert-html-entities.js
  tasks/60_convert-html-entities/convert-html-entities.spec.js
Labels: Ready for merge

#34 [Sophia]Tasks 41 to 50
  tasks/41_sort-by-bits/sort-by-bits.js
  tasks/41_sort-by-bits/sort-by-bits.spec.js
  tasks/42_first-n-smallest/first-n-smallest.js
  tasks/42_first-n-smallest/first-n-smallest.spec.js
  tasks/43_brackets-indexes/brackets-indexes.js
  tasks/43_brackets-indexes/brackets-indexes.spec.js
  tasks/44_time-simulation/time-simulation.js
  tasks/44_time-simulation/time-simulation.spec.js
  tasks/45_equal-sides/equal-sides.js
  tasks/45_equal-sides/equal-sides.spec.js
  tasks/46_running-average/running-average.js
  tasks/46_running-average/running-average.spec.js
  tasks/47_string-expansion/string-expansion.js
  tasks/47_string-expansion/string-expansion.spec.js
  tasks/48_follow-the-spy/follow-the-spy.js
  tasks/48_follow-the-spy/follow-the-spy.spec.js
  tasks/49_cat-and-dog-years/cat-and-dog-years.js
  tasks/49_cat-and-dog-years/cat-and-dog-years.spec.js
  tasks/50_camel-case/camel-case.js
  tasks/50_camel-case/camel-case.spec.js
Labels: Ready for merge, Reviewed

#43 [Eduard Hrabchak] tasks 41-50
  tasks/41_sort-by-bits/sort-by-bits.js
  tasks/41_sort-by-bits/sort-by-bits.spec.js
  tasks/42_first-n-smallest/first-n-smallest.js
  tasks/42_first-n-smallest/first-n-smallest.spec.js
  tasks/43_brackets-indexes/brackets-indexes.js
  tasks/43_brackets-indexes/brackets-indexes.spec.js
  tasks/44_time-simulation/time-simulation.js
  tasks/44_time-simulation/time-simulation.spec.js
  tasks/45_equal-sides/equal-sides.js
  tasks/45_equal-sides/equal-sides.spec.js
  tasks/46_running-average/running-average.js
  tasks/46_running-average/running-average.spec.js
  tasks/47_string-expansion/string-expansion.js
  tasks/47_string-expansion/string-expansion.spec.js
  tasks/48_follow-the-spy/follow-the-spy.js
  tasks/48_follow-the-spy/follow-the-spy.spec.js
  tasks/49_cat-and-dog-years/cat-and-dog-years.js
  tasks/49_cat-and-dog-years/cat-and-dog-years.spec.js
  tasks/50_camel-case/camel-case.js
  tasks/50_camel-case/camel-case.spec.js
Labels: Changes requested, Reviewed

#46 [A.Zhukevych]Tasks 41-50
  .editorconfig
  .eslintrc.json
  README.md
  tasks/41_sort-by-bits/sort-by-bits.js
  tasks/41_sort-by-bits/sort-by-bits.spec.js
  tasks/42_first-n-smallest/first-n-smallest.js
  tasks/42_first-n-smallest/first-n-smallest.spec.js
  tasks/43_brackets-indexes/brackets-indexes.js
  tasks/43_brackets-indexes/brackets-indexes.spec.js
  tasks/44_time-simulation/time-simulation.js
  tasks/44_time-simulation/time-simulation.spec.js
  tasks/45_equal-sides/equal-sides.js
  tasks/45_equal-sides/equal-sides.spec.js
  tasks/46_running-average/running-average.js
  tasks/46_running-average/running-average.spec.js
  tasks/47_string-expansion/string-expansion.js
  tasks/47_string-expansion/string-expansion.spec.js
  tasks/48_follow-the-spy/follow-the-spy.js
  tasks/48_follow-the-spy/follow-the-spy.spec.js
  tasks/49_cat-and-dog-years/cat-and-dog-years.js
  tasks/49_cat-and-dog-years/cat-and-dog-years.spec.js
  tasks/50_camel-case/camel-case.js
  tasks/50_camel-case/camel-case.spec.js
Labels: Ready for merge, Reviewed

#52 [Artur Kostiuk] tasks_41-50
  tasks/41_sort-by-bits/sort-by-bits.js
  tasks/41_sort-by-bits/sort-by-bits.spec.js
  tasks/42_first-n-smallest/first-n-smallest.js
  tasks/42_first-n-smallest/first-n-smallest.spec.js
  tasks/43_brackets-indexes/brackets-indexes.js
  tasks/43_brackets-indexes/brackets-indexes.spec.js
  tasks/44_time-simulation/time-simulation.js
  tasks/44_time-simulation/time-simulation.spec.js
  tasks/45_equal-sides/equal-sides.js
  tasks/45_equal-sides/equal-sides.spec.js
  tasks/46_running-average/running-average.js
  tasks/46_running-average/running-average.spec.js
  tasks/47_string-expansion/string-expansion.js
  tasks/47_string-expansion/string-expansion.spec.js
  tasks/48_follow-the-spy/follow-the-spy.js
  tasks/48_follow-the-spy/follow-the-spy.spec.js
  tasks/49_cat-and-dog-years/cat-and-dog-years.js
  tasks/49_cat-and-dog-years/cat-and-dog-years.spec.js
  tasks/50_camel-case/camel-case.js
  tasks/50_camel-case/camel-case.spec.js
Labels: Ready for merge, Reviewed

#48 [Natalia Falinska] Tasks_31_40
  tasks/31_reverse-string-in-range/reverse-string-in-range.js
  tasks/31_reverse-string-in-range/reverse-string-in-range.spec.js
  tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.js
  tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.spec.js
  tasks/33_array-plus-array/array-plus-array.js
  tasks/33_array-plus-array/array-plus-array.spec.js
  tasks/34_max-triplet-sum/max-triplet-sum.js
  tasks/34_max-triplet-sum/max-triplet-sum.spec.js
  tasks/35_array-leaders/array-leaders.js
  tasks/35_array-leaders/array-leaders.spec.js
  tasks/36_row-weight/row-weight.js
  tasks/36_row-weight/row-weight.spec.js
  tasks/37_min-number-to-prime/min-number-to-prime.js
  tasks/37_min-number-to-prime/min-number-to-prime.spec.js
  tasks/38_max-product/max-product.js
  tasks/38_max-product/max-product.spec.js
  tasks/39_unique-in-order/unique-in-order.js
  tasks/39_unique-in-order/unique-in-order.spec.js
  tasks/40_find-friend/find-friend.js
  tasks/40_find-friend/find-friend.spec.js
Labels: Changes requested, On review

#54 [NATALIYA_MYKYTYUK] Tasks 41-50
  tasks/41_sort-by-bits/sort-by-bits.js
  tasks/41_sort-by-bits/sort-by-bits.spec.js
  tasks/42_first-n-smallest/first-n-smallest.js
  tasks/43_brackets-indexes/brackets-indexes.js
  tasks/43_brackets-indexes/brackets-indexes.spec.js
  tasks/44_time-simulation/time-simulation.js
  tasks/44_time-simulation/time-simulation.spec.js
  tasks/45_equal-sides/equal-sides.js
  tasks/45_equal-sides/equal-sides.spec.js
  tasks/46_running-average/running-average.js
  tasks/46_running-average/running-average.spec.js
  tasks/47_string-expansion/string-expansion.js
  tasks/48_follow-the-spy/follow-the-spy.js
  tasks/48_follow-the-spy/follow-the-spy.spec.js
  tasks/49_cat-and-dog-years/cat-and-dog-years.js
  tasks/49_cat-and-dog-years/cat-and-dog-years.spec.js
  tasks/50_camel-case/camel-case.js
  tasks/50_camel-case/camel-case.spec.js
Labels: Changes requested, Reviewed

#61 [Y_Demkiv] Task 37
  tasks/37_min-number-to-prime/min-number-to-prime.js
  tasks/37_min-number-to-prime/min-number-to-prime.spec.js
Labels: Ready for merge, Reviewed

#49 [Eduard Hrabchak] tasks 51-60
  tasks/51_abbreviated-name/abbreviated-name.js
  tasks/51_abbreviated-name/abbreviated-name.spec.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.spec.js
  tasks/53_diff-array/diff-array.js
  tasks/53_diff-array/diff-array.spec.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.spec.js
  tasks/55_find-object-analogy/find-object-analogy.js
  tasks/55_find-object-analogy/find-object-analogy.spec.js
  tasks/56_search-and-replace/search-and-replace.js
  tasks/56_search-and-replace/search-and-replace.spec.js
  tasks/57_pig-latin/pig-latin.js
  tasks/57_pig-latin/pig-latin.spec.js
  tasks/58_missed-letters/missed-letters.js
  tasks/58_missed-letters/missed-letters.spec.js
  tasks/59_sorted-sequence/sorted-sequence.js
  tasks/59_sorted-sequence/sorted-sequence.spec.js
  tasks/60_convert-html-entities/convert-html-entities.js
  tasks/60_convert-html-entities/convert-html-entities.spec.js
Labels: Changes requested

#44 [TARAS YAKYMIUK]Tasks51 60
  tasks/51_abbreviated-name/abbreviated-name.js
  tasks/51_abbreviated-name/abbreviated-name.spec.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.spec.js
  tasks/53_diff-array/diff-array.js
  tasks/53_diff-array/diff-array.spec.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.spec.js
  tasks/55_find-object-analogy/find-object-analogy.js
  tasks/55_find-object-analogy/find-object-analogy.spec.js
  tasks/56_search-and-replace/search-and-replace.js
  tasks/56_search-and-replace/search-and-replace.spec.js
  tasks/57_pig-latin/pig-latin.js
  tasks/57_pig-latin/pig-latin.spec.js
  tasks/58_missed-letters/missed-letters.js
  tasks/58_missed-letters/missed-letters.spec.js
  tasks/59_sorted-sequence/sorted-sequence.js
  tasks/59_sorted-sequence/sorted-sequence.spec.js
  tasks/60_convert-html-entities/convert-html-entities.js
  tasks/60_convert-html-entities/convert-html-entities.spec.js
Labels: Changes requested, Reviewed

#69 [Y_Demkiv] Tasks 51-60
  tasks/51_abbreviated-name/abbreviated-name.js
  tasks/51_abbreviated-name/abbreviated-name.spec.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.spec.js
  tasks/53_diff-array/diff-array.js
  tasks/53_diff-array/diff-array.spec.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.spec.js
  tasks/55_find-object-analogy/find-object-analogy.js
  tasks/55_find-object-analogy/find-object-analogy.spec.js
  tasks/56_search-and-replace/search-and-replace.js
  tasks/56_search-and-replace/search-and-replace.spec.js
  tasks/57_pig-latin/pig-latin.js
  tasks/57_pig-latin/pig-latin.spec.js
  tasks/58_missed-letters/missed-letters.js
  tasks/58_missed-letters/missed-letters.spec.js
  tasks/59_sorted-sequence/sorted-sequence.js
  tasks/59_sorted-sequence/sorted-sequence.spec.js
  tasks/60_convert-html-entities/convert-html-entities.js
  tasks/60_convert-html-entities/convert-html-entities.spec.js
Labels: Reviewed

#66 [NATALIYA_MYKYTYUK] Tasks 61-70
  tasks/61_spinal-case/spinal-case.js
  tasks/61_spinal-case/spinal-case.spec.js
  tasks/62_swap-cases/swap-cases.js
  tasks/62_swap-cases/swap-cases.spec.js
  tasks/63_insert-string/insert-string.js
  tasks/63_insert-string/insert-string.spec.js
  tasks/64_sum-odd-fibonacci/sum-odd-fibonacci.js
  tasks/64_sum-odd-fibonacci/sum-odd-fibonacci.spec.js
  tasks/65_smaller-common-multiple/smaller-common-multiple.js
  tasks/65_smaller-common-multiple/smaller-common-multiple.spec.js
  tasks/66_sum-primes/sum-primes.js
  tasks/66_sum-primes/sum-primes.spec.js
  tasks/67_find-elements/find-elements.js
  tasks/67_find-elements/find-elements.spec.js
  tasks/68_drop-elements/drop-elements.js
  tasks/68_drop-elements/drop-elements.spec.js
  tasks/69_unpack-elements/unpack-elements.js
  tasks/69_unpack-elements/unpack-elements.spec.js
  tasks/70_binary-decode/binary-decode.js
  tasks/70_binary-decode/binary-decode.spec.js
Labels: Ready for merge, Reviewed

#75 [Pavlo Turchyn]tasks:41-50
  tasks/41_sort-by-bits/sort-by-bits.js
  tasks/41_sort-by-bits/sort-by-bits.spec.js
  tasks/42_first-n-smallest/first-n-smallest.js
  tasks/42_first-n-smallest/first-n-smallest.spec.js
  tasks/43_brackets-indexes/brackets-indexes.js
  tasks/43_brackets-indexes/brackets-indexes.spec.js
  tasks/44_time-simulation/time-simulation.js
  tasks/44_time-simulation/time-simulation.spec.js
  tasks/45_equal-sides/equal-sides.js
  tasks/45_equal-sides/equal-sides.spec.js
  tasks/46_running-average/running-average.js
  tasks/46_running-average/running-average.spec.js
  tasks/47_string-expansion/string-expansion.js
  tasks/47_string-expansion/string-expansion.spec.js
  tasks/48_follow-the-spy/follow-the-spy.js
  tasks/48_follow-the-spy/follow-the-spy.spec.js
  tasks/49_cat-and-dog-years/cat-and-dog-years.js
  tasks/49_cat-and-dog-years/cat-and-dog-years.spec.js
  tasks/50_camel-case/camel-case.js
  tasks/50_camel-case/camel-case.spec.js
Labels: Ready for merge, Reviewed

#78 [Pavlo Turchyn]tasks: 51-60
  tasks/51_abbreviated-name/abbreviated-name.js
  tasks/51_abbreviated-name/abbreviated-name.spec.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.spec.js
  tasks/53_diff-array/diff-array.js
  tasks/53_diff-array/diff-array.spec.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.spec.js
  tasks/55_find-object-analogy/find-object-analogy.js
  tasks/55_find-object-analogy/find-object-analogy.spec.js
  tasks/56_search-and-replace/search-and-replace.js
  tasks/56_search-and-replace/search-and-replace.spec.js
  tasks/57_pig-latin/pig-latin.js
  tasks/57_pig-latin/pig-latin.spec.js
  tasks/58_missed-letters/missed-letters.js
  tasks/58_missed-letters/missed-letters.spec.js
  tasks/59_sorted-sequence/sorted-sequence.js
  tasks/59_sorted-sequence/sorted-sequence.spec.js
  tasks/60_convert-html-entities/convert-html-entities.js
  tasks/60_convert-html-entities/convert-html-entities.spec.js
Labels: Ready for merge, Reviewed

#80 [stas-molchanov]tasks 61-70
  tasks/61_spinal-case/spinal-case.js
  tasks/61_spinal-case/spinal-case.spec.js
  tasks/62_swap-cases/swap-cases.js
  tasks/62_swap-cases/swap-cases.spec.js
  tasks/63_insert-string/insert-string.js
  tasks/63_insert-string/insert-string.spec.js
  tasks/64_sum-odd-fibonacci/sum-odd-fibonacci.js
  tasks/64_sum-odd-fibonacci/sum-odd-fibonacci.spec.js
  tasks/65_smaller-common-multiple/smaller-common-multiple.js
  tasks/65_smaller-common-multiple/smaller-common-multiple.spec.js
  tasks/66_sum-primes/sum-primes.js
  tasks/66_sum-primes/sum-primes.spec.js
  tasks/67_find-elements/find-elements.js
  tasks/67_find-elements/find-elements.spec.js
  tasks/68_drop-elements/drop-elements.js
  tasks/68_drop-elements/drop-elements.spec.js
  tasks/69_unpack-elements/unpack-elements.js
  tasks/69_unpack-elements/unpack-elements.spec.js
  tasks/70_binary-decode/binary-decode.js
  tasks/70_binary-decode/binary-decode.spec.js
Labels: Reviewed

#68 [Eduard Hrabchak] Tasks: 71-80
  tasks/71_binary-encode/binary-encode.js
  tasks/71_binary-encode/binary-encode.spec.js
  tasks/72_carrying/carrying.js
  tasks/72_carrying/carrying.spec.js
  tasks/73_check-for-palindromes/check-for-palindromes.js
  tasks/73_check-for-palindromes/check-for-palindromes.spec.js
  tasks/74_dna-pairing/dna-pairing.js
  tasks/74_dna-pairing/dna-pairing.spec.js
  tasks/75_complementary-dna/complementary-dna.js
  tasks/75_complementary-dna/complementary-dna.spec.js
  tasks/76_deep-object-clone/deep-object-clone.js
  tasks/76_deep-object-clone/deep-object-clone.spec.js
  tasks/77_expressions-matter/expressions-matter.js
  tasks/77_expressions-matter/expressions-matter.spec.js
  tasks/78_valid-braces/valid-braces.js
  tasks/78_valid-braces/valid-braces.spec.js
  tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.js
  tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.spec.js
  tasks/80_sum-of-prime-indexes/sum-of-prime-indexes.js
  tasks/80_sum-of-prime-indexes/sum-of-prime-indexes.spec.js
Labels: Ready for merge, Reviewed

#62 [Sophia]Tasks 71 to 80
  package-lock.json
  package.json
  tasks/71_binary-encode/binary-encode.js
  tasks/71_binary-encode/binary-encode.spec.js
  tasks/72_carrying/carrying.js
  tasks/72_carrying/carrying.spec.js
  tasks/73_check-for-palindromes/check-for-palindromes.js
  tasks/73_check-for-palindromes/check-for-palindromes.spec.js
  tasks/74_dna-pairing/dna-pairing.js
  tasks/74_dna-pairing/dna-pairing.spec.js
  tasks/75_complementary-dna/complementary-dna.js
  tasks/75_complementary-dna/complementary-dna.spec.js
  tasks/76_deep-object-clone/deep-object-clone.js
  tasks/76_deep-object-clone/deep-object-clone.spec.js
  tasks/77_expressions-matter/expressions-matter.js
  tasks/77_expressions-matter/expressions-matter.spec.js
  tasks/78_valid-braces/valid-braces.js
  tasks/78_valid-braces/valid-braces.spec.js
  tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.js
  tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.spec.js
  tasks/80_sum-of-prime-indexes/sum-of-prime-indexes.js
  tasks/80_sum-of-prime-indexes/sum-of-prime-indexes.spec.js
Labels: Ready for merge, Reviewed

#64 [A.Zhukevych]Tasks: 71-80
  tasks/71_binary-encode/binary-encode.js
  tasks/71_binary-encode/binary-encode.spec.js
  tasks/72_carrying/carrying.js
  tasks/72_carrying/carrying.spec.js
  tasks/73_check-for-palindromes/check-for-palindromes.js
  tasks/73_check-for-palindromes/check-for-palindromes.spec.js
  tasks/74_dna-pairing/dna-pairing.js
  tasks/74_dna-pairing/dna-pairing.spec.js
  tasks/75_complementary-dna/complementary-dna.js
  tasks/75_complementary-dna/complementary-dna.spec.js
  tasks/76_deep-object-clone/deep-object-clone.js
  tasks/76_deep-object-clone/deep-object-clone.spec.js
  tasks/77_expressions-matter/expressions-matter.js
  tasks/77_expressions-matter/expressions-matter.spec.js
  tasks/78_valid-braces/valid-braces.js
  tasks/78_valid-braces/valid-braces.spec.js
  tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.js
  tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.spec.js
  tasks/80_sum-of-prime-indexes/sum-of-prime-indexes.js
  tasks/80_sum-of-prime-indexes/sum-of-prime-indexes.spec.js
Labels: Ready for merge, Reviewed

#58 [Eduard Hrabchak] tasks 61-70
  tasks/61_spinal-case/spinal-case.js
  tasks/61_spinal-case/spinal-case.spec.js
  tasks/62_swap-cases/swap-cases.js
  tasks/62_swap-cases/swap-cases.spec.js
  tasks/63_insert-string/insert-string.js
  tasks/63_insert-string/insert-string.spec.js
  tasks/64_sum-odd-fibonacci/sum-odd-fibonacci.js
  tasks/64_sum-odd-fibonacci/sum-odd-fibonacci.spec.js
  tasks/65_smaller-common-multiple/smaller-common-multiple.js
  tasks/65_smaller-common-multiple/smaller-common-multiple.spec.js
  tasks/66_sum-primes/sum-primes.js
  tasks/66_sum-primes/sum-primes.spec.js
  tasks/67_find-elements/find-elements.js
  tasks/67_find-elements/find-elements.spec.js
  tasks/68_drop-elements/drop-elements.js
  tasks/68_drop-elements/drop-elements.spec.js
  tasks/69_unpack-elements/unpack-elements.js
  tasks/69_unpack-elements/unpack-elements.spec.js
  tasks/70_binary-decode/binary-decode.js
  tasks/70_binary-decode/binary-decode.spec.js
Labels: Ready for merge, Reviewed

#59 [stas-molchanov]tasks 51 to 60
  tasks/51_abbreviated-name/abbreviated-name.js
  tasks/51_abbreviated-name/abbreviated-name.spec.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.spec.js
  tasks/53_diff-array/diff-array.js
  tasks/53_diff-array/diff-array.spec.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.spec.js
  tasks/55_find-object-analogy/find-object-analogy.js
  tasks/55_find-object-analogy/find-object-analogy.spec.js
  tasks/56_search-and-replace/search-and-replace.js
  tasks/56_search-and-replace/search-and-replace.spec.js
  tasks/57_pig-latin/pig-latin.js
  tasks/57_pig-latin/pig-latin.spec.js
  tasks/58_missed-letters/missed-letters.js
  tasks/58_missed-letters/missed-letters.spec.js
  tasks/59_sorted-sequence/sorted-sequence.js
  tasks/59_sorted-sequence/sorted-sequence.spec.js
  tasks/60_convert-html-entities/convert-html-entities.spec.js
Labels: Ready for merge, Reviewed

#63 [Artur Kostiuk] tasks_51-60
  tasks/51_abbreviated-name/abbreviated-name.js
  tasks/51_abbreviated-name/abbreviated-name.spec.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
  tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.spec.js
  tasks/53_diff-array/diff-array.js
  tasks/53_diff-array/diff-array.spec.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.js
  tasks/54_roman-numbers-convert/roman-numbers-convert.spec.js
  tasks/55_find-object-analogy/find-object-analogy.js
  tasks/55_find-object-analogy/find-object-analogy.spec.js
  tasks/56_search-and-replace/search-and-replace.js
  tasks/56_search-and-replace/search-and-replace.spec.js
  tasks/57_pig-latin/pig-latin.js
  tasks/57_pig-latin/pig-latin.spec.js
  tasks/58_missed-letters/missed-letters.js
  tasks/58_missed-letters/missed-letters.spec.js
  tasks/59_sorted-sequence/sorted-sequence.js
  tasks/59_sorted-sequence/sorted-sequence.spec.js
  tasks/60_convert-html-entities/convert-html-entities.js
  tasks/60_convert-html-entities/convert-html-entities.spec.js
Labels: Ready for merge, Reviewed

#65 [TARAS YAKYMIUK] Tasks71-80
  tasks/71_binary-encode/binary-encode.js
  tasks/71_binary-encode/binary-encode.spec.js
  tasks/72_carrying/carrying.js
  tasks/72_carrying/carrying.spec.js
  tasks/73_check-for-palindromes/check-for-palindromes.js
  tasks/73_check-for-palindromes/check-for-palindromes.spec.js
  tasks/74_dna-pairing/dna-pairing.js
  tasks/74_dna-pairing/dna-pairing.spec.js
  tasks/75_complementary-dna/complementary-dna.js
  tasks/75_complementary-dna/complementary-dna.spec.js
  tasks/76_deep-object-clone/deep-object-clone.js
  tasks/76_deep-object-clone/deep-object-clone.spec.js
  tasks/77_expressions-matter/expressions-matter.js
  tasks/77_expressions-matter/expressions-matter.spec.js
  tasks/78_valid-braces/valid-braces.js
  tasks/78_valid-braces/valid-braces.spec.js
  tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.js
  tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.spec.js
  tasks/80_sum-of-prime-indexes/sum-of-prime-indexes.js
  tasks/80_sum-of-prime-indexes/sum-of-prime-indexes.spec.js
Labels: Ready for merge, Reviewed

#71 [Artur Kostiuk]tasks_61-70
  tasks/61_spinal-case/spinal-case.js
  tasks/61_spinal-case/spinal-case.spec.js
  tasks/62_swap-cases/swap-cases.js
  tasks/62_swap-cases/swap-cases.spec.js
  tasks/63_insert-string/insert-string.js
  tasks/63_insert-string/insert-string.spec.js
  tasks/64_sum-odd-fibonacci/sum-odd-fibonacci.js
  tasks/64_sum-odd-fibonacci/sum-odd-fibonacci.spec.js
  tasks/65_smaller-common-multiple/smaller-common-multiple.js
  tasks/65_smaller-common-multiple/smaller-common-multiple.spec.js
  tasks/66_sum-primes/sum-primes.js
  tasks/66_sum-primes/sum-primes.spec.js
  tasks/67_find-elements/find-elements.js
  tasks/67_find-elements/find-elements.spec.js
  tasks/68_drop-elements/drop-elements.js
  tasks/68_drop-elements/drop-elements.spec.js
  tasks/69_unpack-elements/README.md
  tasks/69_unpack-elements/unpack-elements.js
  tasks/69_unpack-elements/unpack-elements.spec.js
  tasks/70_binary-decode/binary-decode.js
  tasks/70_binary-decode/binary-decode.spec.js
Labels: Ready for merge, Reviewed

#82 [Sophia]Tasks 81 to 90
  tasks/81_buying-car/buying-car.js
  tasks/81_buying-car/buying-car.spec.js
  tasks/82_bouncing-balls/README.md
  tasks/82_bouncing-balls/bouncing-balls.js
  tasks/82_bouncing-balls/bouncing-balls.spec.js
  tasks/83_missing-term/missing-term.js
  tasks/83_missing-term/missing-term.spec.js
  tasks/84_added-characters/added-characters.spec.js
  tasks/84_added-characters/added_characters.js
  tasks/85_bet-validation/bet-validation.js
  tasks/85_bet-validation/bet-validation.spec.js
  tasks/86_working-hours/working-hours.js
  tasks/86_working-hours/working-hours.spec.js
  tasks/87_validate-us-telephone-number/validate-us-telephone-number.js
  tasks/87_validate-us-telephone-number/validate-us-telephone-number.spec.js
  tasks/88_record-collection/record-collection.js
  tasks/88_record-collection/record-collection.spec.js
  tasks/89_symmertic-difference/symmertic-difference.js
  tasks/89_symmertic-difference/symmertic-difference.spec.js
  tasks/91_inventory-update/inventory-update.js
  tasks/91_inventory-update/inventory-update.spec.js
Labels: Changes requested, Reviewed

#70 [TARAS-YAKYMIUK] Tasks: 81-90
  tasks/27_basic-subclasses/basic-subclasses.js
  tasks/29_remove-duplicates/remove-duplicates.js
  tasks/72_carrying/carrying.spec.js
  tasks/73_check-for-palindromes/check-for-palindromes.spec.js
  tasks/74_dna-pairing/dna-pairing.spec.js
  tasks/75_complementary-dna/complementary-dna.spec.js
  tasks/76_deep-object-clone/deep-object-clone.spec.js
  tasks/77_expressions-matter/expressions-matter.spec.js
  tasks/78_valid-braces/valid-braces.spec.js
  tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.spec.js
  tasks/80_sum-of-prime-indexes/sum-of-prime-indexes.spec.js
  tasks/81_buying-car/buying-car.js
  tasks/81_buying-car/buying-car.spec.js
  tasks/82_bouncing-balls/bouncing-balls.js
  tasks/82_bouncing-balls/bouncing-balls.spec.js
  tasks/83_missing-term/missing-term.js
  tasks/83_missing-term/missing-term.spec.js
  tasks/84_added-characters/added-characters.spec.js
  tasks/84_added-characters/added_characters.js
  tasks/85_bet-validation/bet-validation.js
  tasks/85_bet-validation/bet-validation.spec.js
  tasks/86_working-hours/working-hours.js
  tasks/86_working-hours/working-hours.spec.js
  tasks/87_validate-us-telephone-number/validate-us-telephone-number.js
  tasks/87_validate-us-telephone-number/validate-us-telephone-number.spec.js
  tasks/88_record-collection/record-collection.js
  tasks/88_record-collection/record-collection.spec.js
  tasks/89_symmertic-difference/symmertic-difference.js
  tasks/89_symmertic-difference/symmertic-difference.spec.js
Labels: Changes requested, Reviewed

#74 [Pavlo Turchyn] Tasks 31-40
  tasks/31_reverse-string-in-range/reverse-string-in-range.js
  tasks/31_reverse-string-in-range/reverse-string-in-range.spec.js
  tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.js
  tasks/32_numbers-to-reversed-array/numbers-to-reversed-array.spec.js
  tasks/33_array-plus-array/array-plus-array.js
  tasks/33_array-plus-array/array-plus-array.spec.js
  tasks/34_max-triplet-sum/max-triplet-sum.js
  tasks/34_max-triplet-sum/max-triplet-sum.spec.js
  tasks/35_array-leaders/array-leaders.js
  tasks/35_array-leaders/array-leaders.spec.js
  tasks/36_row-weight/row-weight.js
  tasks/36_row-weight/row-weight.spec.js
  tasks/37_min-number-to-prime/min-number-to-prime.js
  tasks/37_min-number-to-prime/min-number-to-prime.spec.js
  tasks/38_max-product/max-product.js
  tasks/38_max-product/max-product.spec.js
  tasks/39_unique-in-order/unique-in-order.js
  tasks/39_unique-in-order/unique-in-order.spec.js
  tasks/40_find-friend/find-friend.js
  tasks/40_find-friend/find-friend.spec.js
Labels: Changes requested, Reviewed

#94 [Pavlo Turchyn]tasks:81-90
  tasks/81_buying-car/buying-car.js
  tasks/81_buying-car/buying-car.spec.js
  tasks/82_bouncing-balls/bouncing-balls.js
  tasks/82_bouncing-balls/bouncing-balls.spec.js
  tasks/83_missing-term/missing-term.js
  tasks/83_missing-term/missing-term.spec.js
  tasks/84_added-characters/added-characters.js
  tasks/84_added-characters/added-characters.spec.js
  tasks/85_bet-validation/bet-validation.js
  tasks/85_bet-validation/bet-validation.spec.js
  tasks/86_working-hours/working-hours.js
  tasks/86_working-hours/working-hours.spec.js
  tasks/87_validate-us-telephone-number/validate-us-telephone-number.js
  tasks/87_validate-us-telephone-number/validate-us-telephone-number.spec.js
  tasks/88_record-collection/record-collection.js
  tasks/88_record-collection/record-collection.spec.js
  tasks/89_symmertic-difference/symmertic-difference.js
  tasks/89_symmertic-difference/symmertic-difference.spec.js
Labels: Changes requested, Reviewed
