Repository griddynamics/ui-internship-lwo2, pull requests merged in 2018-12, with the labels that each got.

#180 [A.Zhukevych]Interactive-task 3
  css-practice/task3/css/main.css
  css-practice/task3/css/style.min.css
  css-practice/task3/css/style.pre.css
  css-practice/task3/img/service1.png
  css-practice/task3/img/web_design.png
  css-practice/task3/index.html
  css-practice/task3/js/accordion.js
  css-practice/task3/js/menu.js
  css-practice/task3/js/popup.js
  css-practice/task3/js/slider.js
  css-practice/task3/src/pug/_includes/footer.pug
  css-practice/task3/src/pug/_includes/hero.pug
  css-practice/task3/src/pug/_includes/main/about.pug
  css-practice/task3/src/pug/_includes/main/accordion.pug
  css-practice/task3/src/pug/_includes/main/blog.pug
  css-practice/task3/src/pug/_includes/main/feature.pug
  css-practice/task3/src/pug/_includes/main/work.pug
  css-practice/task3/src/pug/index.pug
  css-practice/task3/src/scss/abstract/_variables.scss
  css-practice/task3/src/scss/base/_accordion.scss
  css-practice/task3/src/scss/base/_buttons.scss
  css-practice/task3/src/scss/base/_header.scss
  css-practice/task3/src/scss/base/_modal.scss
  css-practice/task3/src/scss/base/_normalize.scss
  css-practice/task3/src/scss/base/_quote-slide.scss
  css-practice/task3/src/scss/base/_slider.scss
  css-practice/task3/src/scss/base/_utilities.scss
  css-practice/task3/src/scss/layout/_media.scss
  css-practice/task3/src/scss/main.scss
  css-practice/task3/src/scss/sections/_feature.scss
  css-practice/task3/src/scss/sections/_hero.scss
  css-practice/task3/src/scss/sections/_work.scss
  css-practice/task3/src/scss/vendor/_animate.scss
Labels: Ready for merge, Reviewed

#179 [TARAS YAKYMIUK]Task3
  css-practice/task3/workspace/accordion.js
  css-practice/task3/workspace/css/main.css
  css-practice/task3/workspace/index.html
  css-practice/task3/workspace/navbar.js
  css-practice/task3/workspace/popup.js
  css-practice/task3/workspace/scss/_about-us-resp.scss
  css-practice/task3/workspace/scss/_comment.scss
  css-practice/task3/workspace/scss/_common.scss
  css-practice/task3/workspace/scss/_feedback.scss
  css-practice/task3/workspace/scss/_header-resp.scss
  css-practice/task3/workspace/scss/_header.scss
  css-practice/task3/workspace/scss/_nav.scss
  css-practice/task3/workspace/scss/_portfolio.scss
  css-practice/task3/workspace/scss/_service.scss
  css-practice/task3/workspace/slider.js
Labels: Changes requested, Reviewed

#182 [Pavlo Turchyn]Css task 3 sliders
  .gitignore
  css-practice/task_3/css/main.css
  css-practice/task_3/index.html
  css-practice/task_3/script.js
  css-practice/task_3/scss/_header.scss
  css-practice/task_3/scss/_quote.scss
  css-practice/task_3/scss/_reset.scss
  css-practice/task_3/scss/_testimonial.scss
  css-practice/task_3/scss/_we-do.scss
  css-practice/task_3/scss/_work.scss
  css-practice/task_3/scss/main.scss
Labels: Changes requested, Reviewed

#200 [TARAS YAKYMIUK]Fetch task
  css-practice/task3/workspace/blog-item.js
  css-practice/task3/workspace/css/main.css
  css-practice/task3/workspace/fetch-hanler.js
  css-practice/task3/workspace/index.html
  css-practice/task3/workspace/latest-blog.js
  css-practice/task3/workspace/render-process.js
  css-practice/task3/workspace/scss/_blog.scss
  css-practice/task3/workspace/scss/_footer.scss
Labels: Changes requested, Reviewed

#186 [Eduard Hrabchak] Interactive task 3
  css-practice/task3/css/main.css
  css-practice/task3/index.html
  css-practice/task3/js/index.js
  css-practice/task3/scss/main.scss
Labels: Ready for merge, Reviewed

#203 [Nataliia Falinska] MoGo-JS-Task3
  css-practice/task_3/accordion.js
  css-practice/task_3/css/style.css
  css-practice/task_3/header.js
  css-practice/task_3/img/arrow/down_copy.png
  css-practice/task_3/img/arrow/down_copy_2.png
  css-practice/task_3/img/creative.jpg
  css-practice/task_3/img/qw1.png
  css-practice/task_3/img/qw2.png
  css-practice/task_3/img/qw3.png
  css-practice/task_3/img/qw4.png
  css-practice/task_3/img/web2.jpg
  css-practice/task_3/index.html
  css-practice/task_3/popup.js
  css-practice/task_3/scss/_accordion.scss
  css-practice/task_3/scss/_main.scss
  css-practice/task_3/scss/_media.scss
  css-practice/task_3/scss/_modal.scss
  css-practice/task_3/scss/_slider.scss
  css-practice/task_3/scss/style.scss
  css-practice/task_3/slider.js
Labels: Changes requested, Reviewed

#212 [Sofia]Fetch task
  html-template-3/blog.js
  html-template-3/css/main.css
  html-template-3/fetch.js
  html-template-3/index.html
  html-template-3/scss/main.scss
Labels: Ready for merge, Reviewed

#204 [Natalia Falinska] fetch for task3
  css-practice/task_3/css/style.css
  css-practice/task_3/index.html
  css-practice/task_3/index.js
  css-practice/task_3/scss/_main.scss
Labels: Changes requested, Reviewed

#207 [Y_Demkiv] Task 4 blogs fetch
  css-practice/task_3/blog.js
  css-practice/task_3/css/main.css
  css-practice/task_3/index.html
  css-practice/task_3/sass/_style.scss
  package-lock.json
  package.json
Labels: Ready for merge, Reviewed

#210 [Pavlo Turchyn]Fetch from server
  css-practice/task_3/css/main.css
  css-practice/task_3/index.html
  css-practice/task_3/scss/_blog.scss
  css-practice/task_3/scss/_footer.scss
  css-practice/task_3/serverUpdate.js
Labels: Ready for merge, Reviewed

#208 [stas-molchanov]fetch API practice
  css-practice/task-3/css/style.css
  css-practice/task-3/css/style.scss
  css-practice/task-3/index.html
  css-practice/task-3/js/script.js
Labels: Ready for merge, Reviewed

#211 [Eduard Hrabchak] fetch api
  css-practice/task3/css/main.css
  css-practice/task3/index.html
  css-practice/task3/js/fetch-api.js
  css-practice/task3/scss/main.scss
Labels: Ready for merge, Reviewed

#218 [Artur Kostiuk]Page layout
  angular.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/footer/footer.component.html
  src/app/footer/footer.component.scss
  src/app/footer/footer.component.spec.ts
  src/app/footer/footer.component.ts
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/app/main/main.component.html
  src/app/main/main.component.scss
  src/app/main/main.component.spec.ts
  src/app/main/main.component.ts
  src/assets/fonts/HarmoniaSansProCyr-Bold.otf
  src/assets/fonts/HarmoniaSansProCyr-Italic.otf
  src/assets/fonts/HarmoniaSansProCyr-Regular.otf
  src/index.html
  src/sass/_fonts.scss
  src/sass/_reset.scss
  src/sass/_variables.scss
  src/styles.scss
Labels: On review

#221 [Nataliya Mykytyuk] Header details
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/header/header-contacts/header-contacts.component.html
  src/app/header/header-contacts/header-contacts.component.scss
  src/app/header/header-contacts/header-contacts.component.spec.ts
  src/app/header/header-contacts/header-contacts.component.ts
  src/app/header/header-nav/header-nav.component.html
  src/app/header/header-nav/header-nav.component.scss
  src/app/header/header-nav/header-nav.component.spec.ts
  src/app/header/header-nav/header-nav.component.ts
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/header/header.component.spec.ts
  src/app/header/header.component.ts
  src/assets/img/logo.png
  src/assets/img/mail-icon.png
  src/assets/img/phone-icon.png
  src/index.html
  src/sass/_fonts.scss
  src/sass/_reset.scss
  src/sass/_variables.scss
  src/styles.scss
Labels: Reviewed

#224 [Natalia Falinska] Develop network layer service
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/data.service.spec.ts
  src/app/data.service.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: Changes requested
